### ISSUE TITLE
binding.trace_tree returns improper output

### ISSUE THREAD

**Issue by takahashi64** [turnon/trace_tree#1]
On Rails 4.2 I get the following output:
`{:trace=>3.2e-05, :tree=>0.0} undefined method `thread' for nil:NilClass`

**Comment by turnon** [comment]
please provide whole snippet

**Comment by takahashi64** [comment]
Sorry, my mistake:

```
require 'trace_tree'


binding.trace_tree do
  puts "HI!"
end
```

**Comment by turnon** [comment]
It should be no issue for such simple snippet. May I know the context where you run these code? 

Or please try `binding.trace_tree(debug: true) {puts 'HI'}` to dump the trace point list in you tmp dir for debug

Also, please check if you are using the most updated verion

**Comment by takahashi64** [comment]
I pulled down the gem again, and now it works just fine. Thanks for this awesome gem :)
